name: Python CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY || 'dummy-secret-key-for-ci-12345' }}
      DEBUG: False
      DATABASE_URL: sqlite:///db.sqlite3
      USE_SQLITE: True

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml'

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install uv and dependencies
        run: |
          pip install uv
          uv pip install -e .[dev]  # Установка с dev-зависимостями

      - name: Run migrations
        run: |
          python manage.py makemigrations
          python manage.py migrate

      - name: Run tests
        run: |
          python manage.py test

      - name: Run linter
        run: |
          ruff check task_manager

      - name: Generate coverage
        run: |
          pip install coverage
          coverage run --source='.' manage.py test
          coverage xml

      - name: SonarQube Scan
        if: always()
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=darthlivesey_python-project-52
            -Dsonar.organization=darthlivesey
            -Dsonar.python.coverage.reportPaths=coverage.xml